// <auto-generated />
namespace MVCSignalRChatSolution.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ImageIdNuevoCampo_en_Users : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ImageIdNuevoCampo_en_Users));
        
        string IMigrationMetadata.Id
        {
            get { return "201810041625020_ImageIdNuevoCampo_en_Users"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
